### ISSUE TITLE
Metallic Colours for guns 

### ISSUE THREAD

**Issue by ThomasAnderson11** [unknown321/mgsmonsterguns#2]
Hi @unknown321, im really amateur at this.

Apparently the game had planned metallic colours for guns
![c7c469a7372d6632873e9bc8f1ff865d](https://user-images.githubusercontent.com/32452928/32499553-9f306b8e-c3b1-11e7-8f42-c58e64545e3a.png)

Found the folder but i cannot get how to make them properly show in the game or at least change them by another colour without model sawpping since that would only work for myself and other won't be able to see it, i could get the bandana and ismael bandages (mgo) "properly" working by modifying the PurchasedID in the Gear.lua file and unreleased camos aswell by modifying the DefaultPrimaryColour, but there is not a similar table for weapons, so i have no idea how the game handles the weapons colour table, any help guidance or ideas would be much appreciated

i know that this might not be the place to talk about this with you but i could not find a proper way to communicate with you plus the modding scene is not that big for this game.

**Comment by unknown321** [comment]
Honestly, not so sure about mgo weapons - never cared about them at all. 
You can try asking people here - https://discord.gg/qwGuWZ , but they are working with tpp assets, mgo is almost untouched.
